version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/App/Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/App/Nginx/conf.d:/etc/nginx/conf.d:ro
      - /root/App/Nginx/html:/usr/share/nginx/html:ro
      - /root/App/Nginx/logs:/var/log/nginx
    networks:
      - share

networks:
  share:
    external: true
