version: "3"
services:
  mcp-gateway:
    image: ghcr.io/amoylab/unla/mcp-gateway:latest
    container_name: unla-mcp-gateway
    ports:
      - "5235:5235"
    environment:
      - ENV=production
      - TZ=Asia/Shanghai
    volumes:
      - /root/App/Unla/multi/.env:/app/.env
      - /root/App/Unla/multi/data/backend:/app/data
    restart: always
    networks:
      - share

  web:
    image: ghcr.io/amoylab/unla/web:latest
    container_name: unla-web
    ports:
      - "8080:80"
      - "5234:5234"
    environment:
      - ENV=production
      - TZ=Asia/Shanghai
    volumes:
      - /root/App/Unla/multi/.env:/app/.env
      - /root/App/Unla/multi/data/web:/app/data
    depends_on:
      - mcp-gateway
    restart: always
    networks:
      - share


# volumes:
#   web_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./data/web
#   backend_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./data/backend

networks:
  share:
    external: true
